version: 2
updates:
  - package-ecosystem: yarn
    directory: "/frontend"
    schedule:
      interval: "daily"
      updates:
  - package-ecosystem: yarn
    directory: "/backend"
    schedule:
      interval: "daily"
